Shirt.create name: "Rushed to Market", description: "Meta Shirt showing Warning about inability to load shirt", size: "S"
Shirt.create name: "Darwin's Delight", description: "Darwin with paper cutouts of evolution", size: "L"
Shirt.create name: "Victory through Chaos", description: "Button Masher's Manifesto", size: "M"
Shirt.create name: "Console Wars", description: "Gaming consoles as Star Wars battle vehicles", size: "S"
Shirt.create name: "Downtime", description: "Lightsabers charging at an outlet", size: "M"
Shirt.create name: "Shoot First", description: "Solo and Greedo in 8-bit emulating text based game",size: "M"
Shirt.create name: "I Quit!", description: "Stick Figure guy has enough", size: "M"
Shirt.create name: "Family Breakfast", description: "Vader makes eggs for a young Luke and Leia", size: "S"
Shirt.create name: "Music Pirate", description: "Pirate turns to digital piracy", size: "L"
Shirt.create name: "Leonardo", description: "Ninja Turtle as famous painter", size: "L"
Shirt.create name: "My Morning Sidekick", description: "Flying cup of coffee", size: "M"
Shirt.create name: "Casual Friday", description: "Storm Trooper enjoying a casual Friday", size: "M"
Shirt.create name: "WET||SLIPPERY WHEN", description: "Portals used to clean spills", size: "S"
Shirt.create name: "Blending In", description: "Waldo Hiding from some Ninjas!", size: "M"
Shirt.create name: "The Binge", description: "Cookie monster had one to many at the milk bar", size: "M"
Shirt.create name: "Motivation", description: "Training using Bacon as a motivator", size: "S"
Shirt.create name: "Winners at Life", description: "Phoenix, Cat, and Zombie at longevity competition", size: "S"
Shirt.create name: "Halfling Height Requirement", description: "Gandalf as a queue manager", size: "L"
Shirt.create name: "The Last One", description: "Sad Polar Bear is sad", size: "M"
Shirt.create name: "Panda Pirate", description: "Panda as a Pirate", size: "L"